selftests: fix ltm-auto-resume failure caused by top-level results.xml
We recently started saving the combined junit.XML file in the
top-level directory of the aggregated tar.gz file.  This caused the
ltm-auto-resume test to fail with errors:

    Traceback (most recent call last):
      File ".../selftests/util/check_results.py", line 18, in <module>
        results_stats = get_stats_from_dir(args.results)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../test-appliance/files/usr/lib/python3/dist-packages/get_stats.py", line 29, in get_stats_from_dir
        cfg = get_property(testsuite.properties(), 'TESTCFG') or get_property(testsuite.properties(), 'FSTESTCFG')
                           ^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'JUnitXml' object has no attribute 'properties'

Remove the top-level results.xml file if present to avoid this
failure.

Fixes: 88b0870f47d6 ("test-appliance: upload the combined the junit XML...")
Signed-off-by: Theodore Ts'o <tytso@mit.edu>